FROM ruby:3.3.0
ARG UID=1000
ENV LANG C.UTF-8
ENV TZ Asia/Tokyo
ENV BUNDLE_APP_CONFIG /app/.bundle
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev vim
RUN useradd -m -u $UID rails
WORKDIR /app
COPY . /app
RUN chown rails:rails -R /app
