source "https://rubygems.org"

gem "rails", '~> 7.1.0'
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false
gem "rack-cors"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end

gem 'active_model_serializers', '~> 0.10.14'
gem 'devise', '~> 4.9', '>= 4.9.3'
gem 'devise_token_auth', '~> 1.2', '>= 1.2.3'
gem 'omniauth', '~> 2.1', '>= 2.1.2'
gem 'omniauth-rails_csrf_protection', '~> 1.0', '>= 1.0.2'
gem 'omniauth-google-oauth2', '~> 1.2'
gem 'omniauth-discord', '~> 1.2'
gem 'annotate', '~> 3.2'
